// swiftdocs_engine/src/templates/letter.rs
use anyhow::Result;
use printpdf::*;
use serde_json::Value;
use crate::pdf::*;

pub fn render(payload: &Value) -> Result<Vec<u8>> {
    let date       = payload["date"].as_str().unwrap_or("");
    let to_name    = payload["to_name"].as_str().unwrap_or("");
    let subject    = payload["subject"].as_str().unwrap_or("");
    let signatory  = payload["signatory"].as_str().unwrap_or("");
    let designation = payload["designation"].as_str().unwrap_or("");
    let company    = payload["company"].as_str().unwrap_or("");

    let (doc, page1, layer1) = new_a4("Letter — SwiftDocs");
    let layer = doc.get_page(page1).get_layer(layer1);

    let font_regular = doc.add_builtin_font(BuiltinFont::Helvetica)?;
    let font_bold    = doc.add_builtin_font(BuiltinFont::HelveticaBold)?;

    fill_rect(&layer, 0.0, 0.0, A4_W, A4_H, 255, 255, 255);

    // Top accent
    fill_rect(&layer, 0.0, A4_H - 2.5, A4_W, 2.5, 0, 113, 227);

    // Company header
    draw_text(&layer, &font_bold,    company,      8.0, A4_H - 16.0, 14.0, 29, 29, 31);
    draw_text(&layer, &font_regular, "swiftdocs.io", 8.0, A4_H - 23.0, 7.5, 110, 110, 115);

    h_rule(&layer, 8.0, A4_H - 28.0, A4_W - 16.0, 0.4, 210, 210, 215);

    // Date
    draw_text(&layer, &font_regular, date, 8.0, A4_H - 38.0, 9.0, 29, 29, 31);

    // Addressee
    let mut ay = A4_H - 50.0;
    draw_text(&layer, &font_bold, to_name, 8.0, ay, 9.0, 29, 29, 31);
    if let Some(addrs) = payload["to_address"].as_array() {
        for addr in addrs {
            ay -= 6.0;
            draw_text(&layer, &font_regular, addr.as_str().unwrap_or(""), 8.0, ay, 8.5, 29, 29, 31);
        }
    }

    ay -= 10.0;
    draw_text(&layer, &font_regular, "Dear Sir/Madam,", 8.0, ay, 9.0, 29, 29, 31);

    // Subject
    ay -= 8.0;
    draw_text(&layer, &font_bold, &format!("RE: {subject}"), 8.0, ay, 9.0, 29, 29, 31);
    h_rule(&layer, 8.0, ay - 1.5, A4_W - 16.0, 0.4, 0, 113, 227);

    // Body paragraphs
    ay -= 10.0;
    if let Some(paragraphs) = payload["body"].as_array() {
        for para in paragraphs {
            let text = para.as_str().unwrap_or("");
            // Simple word-wrap: 95 chars per line @ 8.5pt
            let words: Vec<&str> = text.split_whitespace().collect();
            let mut line = String::new();
            for word in &words {
                if line.len() + word.len() + 1 > 90 {
                    draw_text(&layer, &font_regular, &line, 8.0, ay, 8.5, 29, 29, 31);
                    ay -= 6.0;
                    line = word.to_string();
                } else {
                    if !line.is_empty() { line.push(' '); }
                    line.push_str(word);
                }
                if ay < 30.0 { break; }
            }
            if !line.is_empty() {
                draw_text(&layer, &font_regular, &line, 8.0, ay, 8.5, 29, 29, 31);
            }
            ay -= 10.0;
            if ay < 30.0 { break; }
        }
    }

    // Sign-off
    ay -= 4.0;
    draw_text(&layer, &font_regular, "Yours faithfully,", 8.0, ay, 8.5, 29, 29, 31);
    ay -= 16.0;
    draw_text(&layer, &font_bold, "_____________________________", 8.0, ay, 8.5, 29, 29, 31);
    ay -= 6.0;
    draw_text(&layer, &font_bold, signatory, 8.0, ay, 9.0, 29, 29, 31);
    ay -= 6.0;
    draw_text(&layer, &font_regular, designation, 8.0, ay, 8.5, 110, 110, 115);
    ay -= 6.0;
    draw_text(&layer, &font_regular, &format!("For and on behalf of: {company}"), 8.0, ay, 8.5, 29, 29, 31);

    // Footer
    fill_rect(&layer, 0.0, 0.0, A4_W, 10.0, 29, 29, 31);
    fill_rect(&layer, 0.0, 9.5, A4_W, 0.8, 0, 113, 227);
    draw_text(&layer, &font_regular, "Generated by SwiftDocs  ·  swiftdocs.io",
              8.0, 3.0, 6.0, 128, 128, 135);

    let mut buf = std::io::BufWriter::new(Vec::new());
    doc.save(&mut buf)?;
    Ok(buf.into_inner().unwrap())
}
